server:
  port: 9002
spring:
  application:
    name: board-game-buddy
  ai:
    openai:
      api-key: ${SPRING_AI_OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4.1-nano
#          top-p: 0.8
#          temperature: 0.5

    vectorstore:
      qdrant:
        initialize-schema: true
        collection-name: board-game-buddy


logging:
  level:
    org.zalando.logbook: TRACE

logbook:
  format:
    style: http

